spring:
  profiles:
    include: core
  datasource:

    type: com.alibaba.druid.pool.DruidDataSource

    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://localhost:3306/blibili?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123
server:
  port: 20535
  tomcat:

    basedir: /data/services/academy-project-server/home/logs/run

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.blibli.academy: DEBUG
