spring:
  profiles:
    include: core
  datasource:
    # 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库url
    url: jdbc:mysql://localhost:3306/blibili?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123
server:
  port: 20534
  tomcat:
    # 环境变量
    basedir: /data/services/academy-project-server/admin/temp

logging:
  level:
    com.blibli.academy: DEBUG
