# 核心配置
spring:
  application:
    name: academy-project
# HTTP ENCODING
  http:
      multipart:
          max-file-size: 2MB
          max-request-size: 10MB
          enabled: true
          file-size-threshold: 0
      encoding:
          enabled: true
          charset: UTF-8
          force: true
  messages:
      encoding: UTF-8
  jmx:
      enabled: true
      default-domain: agentservice
  resources:
      chain:
          strategy:
              content:
                  enabled: true
                  paths: /**
project:
  druid:
    # druid访问用户名（默认：controller）
    username: test
    # druid访问密码（默认：controller）
    password: test
    # druid访问地址（默认：/druid/*）
    servletPath: /druid/*
    # 启用重置功能（默认false）
    resetEnable: false
    # 白名单(非必填)， list
    allowIps[0]:
    # 黑名单(非必填)， list
    denyIps[0]:
  qiniu:
    access_key_id: 6TXc9AIzZ0cWmCbnXPNWOWsf9r2X0rctjvKp-wVn
    access_key_secret: DvWrjs1hkOyJdHw-V7cnW4RUY_RWVBq4SmO19qw6
    bucket_name: images
    # 地区
    endpoint: zone1
    file_url: http://pb2qkinxf.bkt.clouddn.com/

  alySMS:
    accessKeyId: LTAI0BfDbJOsdSCv
    accessKeySecret: 6qgU9HPPKinZCQNYeXWoTCOqS7sjTg
    signName: 李琪
    templateCode: SMS_139445213
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    regionId: cn-hangzhou
    dateFormat: yyyyMMdd
    endpointName: cn-hangzhou
server:
  session:
    timeout: 7200
  context-path: /a
  # HTTP请求和响应头的最大量, 以字节为单位, 默认值为4096, 超过此长度的部分不予处理, 一般为8k. 解决java.io.EOFException: null问题
  max-http-header-size: 8192
  # 请求是否允许X-Forwarded-*
  use-forward-headers: true
  compression:
    # 是否开启压缩，默认为false.
    enabled: true
    # 执行压缩的阈值，默认为2048
    min-response-size: 1024
    # 指定要压缩的MIME type，多个以逗号分隔.
    mime-types: text/plain,text/css,text/xml,text/javascript,application/json,application/javascript,application/xml,application/xml+rss,application/x-javascript,application/x-httpd-php,image/jpeg,image/gif,image/png
  tomcat:
    # 设定remote IP的header，如果remoteIpHeader有值，则设置为RemoteIpValve
    remote-ip-header: X-Forwarded-for
    # 设定Header包含的协议，通常是 X-Forwarded-Proto，如果remoteIpHeader有值，则将设置为RemoteIpValve.
    protocol-header: X-Forwarded-Proto
    # 设定http header使用的，用来覆盖原来port的value.
    port-header: X-Forwarded-Port
    # 设定URI的解码字符集.
    uri-encoding: UTF-8

# MyBatis
mybatis:
    # 多个包加 ,
    type-aliases-package: com.blibli.academy.project.Business.dto,com.blibli.academy.project.query,com.blibli.academy.project.Business.pojo
    mapper-locations: classpath:/mybatis/*.xml
    configuration:
      map-underscore-to-camel-case: true
# mapper
mapper:
    mappers:
        - com.blibli.academy.project.mapperplus.BaseMapper
    not-empty: false
    identity: MYSQL
# pagehelper
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
banner:
    charset: UTF-8
# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring.redis:
  database: 0
# Redis服务器地址
  host: localhost
# Redis服务器连接端口
  port: 6379
# 连接池最大连接数（使用负值表示没有限制）
  pool:
    max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
# 连接池中的最大空闲连接
    max-idle: 8
# 连接池中的最小空闲连接
    min-idle: 0
# 连接超时时间（毫秒）
  timeout: 0
